### ISSUE TITLE
Transmuted Spell - Destructive Wrath not triggering

### ISSUE THREAD

**Issue by erickvieira** [darkcharl/metamagic-extended#19]
The Tempest Domain's [Destructive Wrath](https://bg3.wiki/wiki/Destructive_Wrath) abitily is not triggred when I cast a spell (lets say: Fireball) transmuted to lightning or thunder.

I'm not sure if it was intended, just reporting for those who might face the same issue.

**Comment by darkcharl** [comment]
Thanks for the heads up! 

Transmutation happens in the phase where damage is dealt. I suspect that the check for Destructive Wrath may happen before damage is dealt. 

In tabletop there [are similar issues](https://rpg.stackexchange.com/questions/177824/how-does-the-transmuted-spell-metamagic-work-with-flames-of-phlegethos) where Transmutation may happen *after* another effect. 

Unfortunately I don't think this can be changed with the current engine and implementation. New features might get supported though by Larian, if we get to modify damage in UnlockSpellVariant(), for instance. 

I'll sniff around though to see if there is a workaround as it'd be mighty cool if this combo worked! :)

**Comment by erickvieira** [comment]
Hey! Thanks for the response.

> I'll sniff around though to see if there is a workaround as it'd be mighty cool if this combo worked! :)

Absolutely! It's amazing! It could be cooler if the animations also change to reflect the selected element. But, anyways...

I'm not familiar with BG3 modding but maybe I can figure it out by myself and contribute with a humble PR. Could you provide some sort of instructions on README of how to test locally in my game? Or maybe just a quick start guide from someone else.

Thanks.
